In [5]:
import numpy as np  

In [6]:
#Matrix_M =([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
#let matrix be M
matrix_M = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(matrix_M)



[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [9]:
#(i)Compute an Inversion of the matrix(Transpose)
matrix_M = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
inverse_M = np.linalg.inv(matrix_M)

print(inverse_M)



[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [10]:
#Compute the (deteminant) of the matrix if  possible
matrix_M = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
determinant_M = np.linalg.det(matrix_M)

print(determinant_M)


0.2299999999999999


In [11]:
#Decompose the matrix
#Start with the original matrix M:

M = [[1, 0.2, 0.5],
[0.2, 1, 0.8],
[0.5, 0.8, 1]]

#Initialize the L and U matrices with the same shape as M, filled with zeros:

L = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

U = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

#diagonal elements of L with ones:

L = [[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]


In [12]:
#Transform the matrix
matrix_M.T


array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])